### ISSUE TITLE
Install from specific source

### ISSUE THREAD

**Issue by rejeep** [cask/cask#212] opened 2014-05-23 06:09 UTC
Emacs 24.4 supports installing packages from specific sources using `package-pinned-archives` (see http://www.reddit.com/r/emacs/comments/264dz0/getting_stable_packages_from_melpa/choadpr).

Cask could support this using a syntax like this:

``` lisp
(depends-on "foo" :source melpa)
(depends-on "bar" :source melpa-stable)
```

**Comment by Fuco1** [comment] 2018-09-04 16:57
Duplicate of #252

**Closed by Fuco1** 2018-09-04 16:57 UTC
Labels: duplicate
