### ISSUE TITLE
Cask won't install package dependencies

### ISSUE THREAD

**Issue by lxsameer** [cask/cask#303] opened 2015-07-05 11:58 UTC
Cask won't install package dependencies of a package which I used `link` to develop them. I already generated the pkg-info file

**Comment by rejeep** [comment] 2015-07-11 08:08
Some more information please. How can I reproduce it?

**Comment by ebpa** [comment] 2016-10-14 02:23
@rejeep I think they are referring to the fact that `cask link` does not install dependencies of the linked package; it merely creates the proper symlink.

I suspect that most people use `cask link` for basic symlink replacement of fetchable packages.  Say for example I am wanting to work with unmerged changes to f.el in my current package which uses cask.  After running `cask install` I run `cask link f ../f.el` and presto I'm working with my local copy.  This is less than ideal, however; because f.el's dependencies (s and dash) are only available because f.el was previously fetched and the downloaded s and dash packages remain.

Things fall apart when a direct dependency (say that it's called "my-package.el") does not exist in a remote repository.  `cask install` lists the package missing as we expect.  `cask link my-package ../my-package.el` creates the symlink.  Any dependencies of my-package.el are not installed though.

In cases which the library has not yet been pushed to a package repository it seems reasonable that a vanilla depends-on can be used with `cask link` (and not relying on a workaround with a local fetcher path).

I imagine there are at least two ways of resolving this.

1. **Expand load-path** - Rely on `cask install` having been called on the linked package and recursively build the load-path.
2. **Install linked package dependencies** (either at the time of linking-- preferred OR with a successive `cask install` command)  Pretty straightforward, but links on linked packages likely need to be re-created by hand.
3. **Maintain a system/user global linking index** Something like npm's link behavior in addition to option 2.

Locally I've modified cask.el for option 2, but don't have a clean solution for links with links.

**Comment by rejeep** [comment] 2016-10-17 18:36
Number 2 would be my choice as well. It's easy to find dependencies of links, for example:

```lisp
(-map 'cask-dependency-name
      (let ((bundle (cask-setup "~/Code/f.el")))
        (cask-dependencies bundle)))
```

Closing this. If someone wants to open a PR that implements this I don't mind adding support for it.

**Closed by rejeep** 2016-10-17 18:36 UTC
