### ISSUE TITLE
cask build exit code on compilation error

### ISSUE THREAD

**Issue by razzmatazz** [cask/cask#406] opened 2017-11-16 07:19 UTC
Would it be possible to make `cask build` return a non-0 exit code if there is at least one byte compilation error? When invoked with an extra flag if changing the default behaviour is unacceptable.

I am using `cask install` and `cask build` for our CI in https://github.com/OmniSharp/omnisharp-emacs and now I have to resort to this line, to make the CI build fail when there has been a compilation error encountered:
 - https://github.com/OmniSharp/omnisharp-emacs/pull/403/files#diff-a0da5e0ec10d75f0a10dfd2864c0d124R30

**Comment by rejeep** [comment] 2017-11-17 19:39
I'm closing this as a duplicate of https://github.com/cask/cask/issues/350 and https://github.com/cask/cask/pull/351.

**Closed by rejeep** 2017-11-17 19:39 UTC
