### ISSUE TITLE
Package 's-' is unavailable

### ISSUE THREAD

**Issue by Narven** [cask/cask#373] opened 2016-11-02 16:24 UTC
>I found some other similar errors and people complaning, but they were old (March 2016), and not useful.

On emacs 25.1.1 when I run `cask` inside my .emacs.d folder i get:

```
Contacting host: melpa.org:443
Opening TLS connection to ‘melpa.org’...
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 melpa.org’...
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 melpa.org’...failed
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 melpa.org --protocols ssl3’...
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 melpa.org --protocols ssl3’...failed
Opening TLS connection with ‘openssl s_client -connect melpa.org:443 -no_ssl2 -ign_eof’...
Opening TLS connection with ‘openssl s_client -connect melpa.org:443 -no_ssl2 -ign_eof’...failed
Opening TLS connection to ‘melpa.org’...failed
Failed to download ‘melpa’ archive.
Opening TLS connection to ‘elpa.gnu.org’...
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 elpa.gnu.org’...
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 elpa.gnu.org’...failed
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 elpa.gnu.org --protocols ssl3’...
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 elpa.gnu.org --protocols ssl3’...failed
Opening TLS connection with ‘openssl s_client -connect elpa.gnu.org:443 -no_ssl2 -ign_eof’...
Opening TLS connection with ‘openssl s_client -connect elpa.gnu.org:443 -no_ssl2 -ign_eof’...failed
Opening TLS connection to ‘elpa.gnu.org’...failed
Package refresh done
Failed to download ‘gnu’ archive.
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
Package ‘s-’ is unavailable
```

Its complaining connection to melpa elpa and all the other stuff.

I can install packages from emacs, so I have connection to melpa.

Are the cask configurations to setup those repositories wrong? Or anybody have any other ideas?

thanks

**Comment by Narven** [comment] 2016-11-02 17:15
On of the commands it runs is `gnutls-cli --x509cafile nil -p 443 melpa.org --protocols ssl3`.

If i run that command manually on the terminal, i get:

```
$ gnutls-cli --x509cafile nil -p 443 melpa.org --protocols ssl3
/usr/local/bin/gnutls-cli: illegal option -- protocols
Usage: gnutls-cli [options] hostname
gnutls-cli --help for usage instructions.
```

**Comment by Narven** [comment] 2016-11-02 17:24
After looking at the command `gnutls-cli --help` it does not have a flag `--protocols` also on their website there is not any reference to it. https://gnutls.org/manual/html_node/gnutls_002dcli-Invocation.html

**Comment by lunaryorn** [comment] 2016-11-02 17:27
@Narven That looks like a TLS issue and not related to Cask… do you have two different versions of` gnutls-cli` on your system?  What system are you on actually?

**Comment by Narven** [comment] 2016-11-02 17:28
macOS sierra 10.12.1

**Comment by lunaryorn** [comment] 2016-11-02 17:29
How did you install gnutls and emacs?  Please provide more details about your setup.

**Comment by Narven** [comment] 2016-11-02 17:32
I don't remember ever installing gnutls, but if I did was using `brew install gnutls`. Emacs i installed the only way i know: `brew install emacs --with-cocoa`

What more info do you need?

**Comment by Narven** [comment] 2016-11-02 17:37
$ brew info gnutls
gnutls: stable 3.4.16 (bottled)
GNU Transport Layer Security (TLS) Library
https://gnutls.org/
/usr/local/Cellar/gnutls/3.4.16 (1,115 files, 6.9M) *
  Poured from bottle on 2016-11-02 at 17:31:08
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gnutls.rb
==> Dependencies
Build: pkg-config ✔
Required: libtasn1 ✔, gmp ✔, nettle ✔
Optional: guile ✘, unbound ✘
==> Options
--with-guile
	Build with guile support
--with-unbound
	Build with unbound support

**Comment by lunaryorn** [comment] 2016-11-02 17:38
Can you also show `brew info emacs`?

**Comment by Narven** [comment] 2016-11-02 17:38
```
$ brew info emacs
emacs: stable 25.1 (bottled), HEAD
GNU Emacs text editor
https://www.gnu.org/software/emacs/
/usr/local/Cellar/emacs/25.1 (4,046 files, 118.5M) *
  Built from source on 2016-10-22 at 13:41:17 with: --with-cocoa
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/emacs.rb
==> Dependencies
Build: pkg-config ✔
Optional: dbus ✘, gnutls ✔, librsvg ✔, imagemagick ✔, mailutils ✘
==> Options
--with-cocoa
	Build a Cocoa version of emacs
--with-ctags
	Don't remove the ctags executable that emacs provides
--with-dbus
	Build with dbus support
--with-gnutls
	Build with gnutls support
--with-imagemagick
	Build with imagemagick support
--with-librsvg
	Build with librsvg support
--with-mailutils
	Build with mailutils support
--with-modules
	Compile with dynamic modules support
--without-libxml2
	Don't build with libxml2 support
--HEAD
	Install HEAD version
==> Caveats
Please try the Cask for a better-supported Cocoa version:
  brew cask install emacs

To have launchd start emacs now and restart at login:
  brew services start emacs
Or, if you don't want/need a background service you can just run:
  emacs

.app bundles were installed.
Run `brew linkapps emacs` to symlink these to /Applications.
```

**Comment by lunaryorn** [comment] 2016-11-02 17:42
@Narven Can you try to rebuild with `--with-gnutls` as well?

**Comment by Narven** [comment] 2016-11-02 17:42
that is exactly what I'm doing now

**Comment by Narven** [comment] 2016-11-02 17:47
no luck.

when i run `gnutls-cli --x509cafile nil -p 443 melpa.org` I'm getting:

```
- Status: The certificate is NOT trusted. The certificate issuer is unknown.
*** PKI verification of server certificate failed...
*** Fatal error: Error in the certificate.
*** Handshake has failed
GnuTLS error: Error in the certificate.
```

**Comment by lunaryorn** [comment] 2016-11-02 17:57
Oh, so it can't even verify MELPA's certificate outside of Emacs?  I'm sorry but that's being my capability to fix.  I've never seen that before… is your network ok?  Are you behind some kind of a company proxy?

**Comment by Narven** [comment] 2016-11-02 18:01
I'm trying from my company network, but im not behind a proxy. And I have the same issue at home. I can try in a few minutes at home, since I added the --with-gnutls.

But don't think will make a diference. On my work mac (which is on the same network) I can use cask normaly. So I dont understand whats wrong with the instalation on my mac.

**Comment by lunaryorn** [comment] 2016-11-02 18:08
@Narven Maybe a setup issue with gnutls?  I'm sorry but I really have no idea.

It's not a problem in Cask, however, so I'll close this issue, but please continue this discussion; maybe we can still figure out what's wrong.

**Comment by Narven** [comment] 2016-11-02 18:09
sure... im pretty sure is not an issue with cask now. i will try to investigate a bit more.

**Comment by cjhowe** [comment] 2016-12-21 15:15
I've got the exact same problem with a brand new OS X install. I'm not using Homebrew; I've actually installed both emacs and gnutls with [nix](https://nixos.org).

**Comment by JJ** [comment] 2016-12-27 08:10
Same problem here https://travis-ci.org/perl6/perl6-mode/builds/186829676

**Comment by JJ** [comment] 2016-12-27 08:32
And this definitely looks relevant here http://stackoverflow.com/questions/36338528/emacss-package-install-inserts-an-extra-dash-at-the-end-of-the-package

**Comment by cjhowe** [comment] 2016-12-27 13:10
Can you try again? I don't have this problem anymore, and I changed nothing. I think maybe MELPA had a broken SSL certificate for a bit. Or maybe it's just due to me being on a new network.

**Comment by JJ** [comment] 2016-12-27 13:22
It works fine locally, but repeatedly fails from Travis:
https://travis-ci.org/perl6/perl6-mode
I have tried to fork and eliminate the bootstrap phase, but it fails
anyways, on some other phase. The unchanged versions of cask are in the
first bits of the history.
I'll try it anyway and come back here.

**Comment by JJ** [comment] 2016-12-27 13:27
No way. Same error:
https://travis-ci.org/perl6/perl6-mode/builds/186961898

**Comment by JJ** [comment] 2016-12-27 13:37
Can we disable Melpa meanwhile?

**Comment by JJ** [comment] 2016-12-27 13:50
It would be useless. It's failing with _both_ melpa and elpa. 
My impression is that it's using an upstream library that has somehow changed. Could that be the case?

**Comment by JJ** [comment] 2016-12-27 14:06
I have modified my fork to change to http, since there seemed to be a problem with the secure connection, and adding marmalade while I was at it, but still the same problem https://travis-ci.org/perl6/perl6-mode/builds/186968350

**Comment by Narven** [comment] 2016-12-27 15:03
Hi,

thanks for the responses, but I've decided to start using `use-package`.

**Comment by josteink** [comment] 2017-03-07 06:32
I'm getting the same error when trying to install/use cask on Windows (and yes, I've followed the [Windows installation instructions]).

Anyone else having similar issues?

**Comment by igajsin** [comment] 2017-03-18 12:48
Hi josteink, maybe it related with that issue: http://paste.openstack.org/show/603263/

**Comment by josteink** [comment] 2017-03-20 13:16
That sounds reasonable. If establishing SSL trust to the package-store fails, obviously getting the dependant packages is going to fail too.

Issuing the commands linked in that post manully against ELPA and MELPA yields the following results:

````
C:\>gnutls-cli --x509cafile nil -p 443 elpa.gnu.org
Error setting the x509 trust file
Resolving 'elpa.gnu.org'...
Connecting to '208.118.235.89:443'...
- Certificate type: X.509
- Got a certificate list of 3 certificates.
- Certificate[0] info:
 - subject `CN=elpa.gnu.org', issuer `C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3', RSA key 2048 bits, signed using RSA-SHA256, activated `2017-03-09 17:32:00 UTC', expires `2017-06-07 17:32:00 UTC', SHA-1 fingerprint `7bc21e1349b2211cfb3f0407e389653d01c51212'
        Public Key ID:
                80c76f6c86a8213fcab8fd512ab2bb9b3499054e
        Public key's random art:
                +--[ RSA 2048]----+
                |                 |
                |     o           |
                | E  . +          |
                |o .  o =         |
                |..... o S        |
                | o+o o +         |
                |.== o            |
                |+*.o .           |
                |X*...            |
                +-----------------+

- Certificate[1] info:
 - subject `CN=elpa.gnu.org', issuer `C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3', RSA key 2048 bits, signed using RSA-SHA256, activated `2017-03-09 17:32:00 UTC', expires `2017-06-07 17:32:00 UTC', SHA-1 fingerprint `7bc21e1349b2211cfb3f0407e389653d01c51212'
- Certificate[2] info:
 - subject `C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3', issuer `O=Digital Signature Trust Co.,CN=DST Root CA X3', RSA key 2048 bits, signed using RSA-SHA256, activated `2016-03-17 16:40:46 UTC', expires `2021-03-17 16:40:46 UTC', SHA-1 fingerprint `e6a3b45b062d509b3382282d196efe97d5956ccb'
- Status: The certificate is NOT trusted. The certificate issuer is unknown.
*** PKI verification of server certificate failed...
*** Fatal error: Error in the certificate.
*** Handshake has failed
GnuTLS error: Error in the certificate.

C:\>gnutls-cli --x509cafile nil -p 443 melpa.org
Error setting the x509 trust file
Resolving 'melpa.org'...
Connecting to '104.236.16.183:443'...
- Certificate type: X.509
- Got a certificate list of 2 certificates.
- Certificate[0] info:
 - subject `CN=melpa.org', issuer `C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3', RSA key 2048 bits, signed using RSA-SHA256, activated `2017-03-13 08:30:00 UTC', expires `2017-06-11 08:30:00 UTC', SHA-1 fingerprint `d5d1bc779d3eacec20e2a280967c6e01945da97d'
        Public Key ID:
                2277d087c3575b698bcef0f0981cf2490d00d1b0
        Public key's random art:
                +--[ RSA 2048]----+
                |      +=..  . .. |
                |       +.... oo  |
                |      E = oo.o . |
                |       ..+= o .  |
                |    . o S= %     |
                |     o o  * =    |
                |                 |
                |                 |
                |                 |
                +-----------------+

- Certificate[1] info:
 - subject `C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3', issuer `O=Digital Signature Trust Co.,CN=DST Root CA X3', RSA key 2048 bits, signed using RSA-SHA256, activated `2016-03-17 16:40:46 UTC', expires `2021-03-17 16:40:46 UTC', SHA-1 fingerprint `e6a3b45b062d509b3382282d196efe97d5956ccb'
- Status: The certificate is NOT trusted. The certificate issuer is unknown.
*** PKI verification of server certificate failed...
*** Fatal error: Error in the certificate.
*** Handshake has failed
GnuTLS error: Error in the certificate.
````

Are there any known workarounds?

**Comment by VlachJosef** [comment] 2017-05-20 17:35
I've hit the same issue.
To fix it I run these two commands:

```
(add-to-list 'package-archives (cons "melpa" "https://melpa.org/packages/"))
(package-refresh-contents)
```
Second command gave me a warning about invalid certificate as per @josteink comment.
I've confirmed it by answering `Always` (pressing `A` key).

After that `cask` command run successfully.

**Comment by VlachJosef** [comment] 2017-05-20 19:56
<img width="788" alt="screen shot 2017-05-20 at 8 55 27 pm" src="https://cloud.githubusercontent.com/assets/5246747/26278940/b3ae8be8-3d9e-11e7-9e07-1c31c1587450.png">

**Comment by nhessler** [comment] 2017-06-01 18:06
I have a brand new setup mac OSX 10.12.5, Emacs 25.2 (installed from homebrew cask), cask (from homebrew) and am trying to get cask working to better manage my config. I'm getting this same error.

```
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: melpa.org:443
Failed to download ‘melpa’ archive.
Package refresh done
Failed to download ‘gnu’ archive.
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
Package ‘s-’ is unavailable
```

not sure how to proceed. none of the cask commands work. not `cask install --versbose` or `cask install --debug`. I just get this same message for everything I do with cask. I've also tried the `verbose` and `debug` flags before the `install`, etc. commands.

**Comment by VlachJosef** [comment] 2017-06-01 18:15
@nhessler Have you followed the instructions in my comment? https://github.com/cask/cask/issues/373#issuecomment-302887562

**Comment by Bost** [comment] 2017-10-02 14:15
@VlachJosef Thanx for the hint. I my case the problem was in the corporate firewall. (see my workaround 
9c62718)

**Comment by josteink** [comment] 2017-10-02 14:17
Anyone have any better work-around for CI-like environments where humans wont be around to ignore SSL-settings?

Specifically something which is easy to deploy/setup using Travis-CI.

**Comment by Bost** [comment] 2017-10-02 14:26
@josteink I guess the proxy problem might be a bigger one. See https://github.com/syl20bnr/spacemacs/issues/5698. Also when installing:
```
$ curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```
This is also caused by the proxy so I ended up using `wget` to get the `go` file.

**Comment by Bost** [comment] 2017-10-02 14:28
@josteink ... and while at it - please consider renaming the `go` file to `go.py` or even better `install.py`.

**Comment by k-bx** [comment] 2017-10-16 13:08
Hi. I have the same problem on Ubuntu 14.04.5:

```
ubuntu@builder:~/workspace/minimal-dotemacs$ curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
Cloning into '/home/ubuntu/.cask'...
remote: Counting objects: 3431, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 3431 (delta 1), reused 5 (delta 0), pack-reused 3419
Receiving objects: 100% (3431/3431), 1.10 MiB | 22.11 MiB/s, done.
Resolving deltas: 100% (1925/1925), done.
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: melpa.org:443
Contacting host: melpa.org:443
Failed to download ‘gnu’ archive.
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
Package ‘s-’ is unavailable
Cask could not be bootstrapped. Try again later, or report an issue at https://github.com/cask/cask/issues
ubuntu@builder:~/workspace/minimal-dotemacs$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

The workaround from https://github.com/cask/cask/issues/373#issuecomment-302887562 doesn't help.

**Comment by k-bx** [comment] 2017-10-16 13:14
Also, why does it try to download the `gnu` archive even if it's not set in `Cask` nor `~/.emacs`?

**Comment by k-bx** [comment] 2017-10-16 13:43
Update: what helped was commenting out the line with "gnu" in it in `~/.cask/cask-cli.el` and `~/.cask/cask-bootstrap.el`.

**Comment by yewton** [comment] 2018-01-23 12:22
On `GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-09-13`,

I had to add 

```elisp
(require 'gnutls)
(add-to-list 'gnutls-trustfiles "/private/etc/ssl/cert.pem")
```

to `cask-cli.el`.

cf. https://emacs.stackexchange.com/questions/18045/how-can-i-retrieve-an-https-url-on-mac-os-x-without-warnings-about-an-untrusted/35953#35953

**Comment by sambrightman** [comment] 2018-01-23 15:53
I think this ticket is rather outliving its usefulness and is mostly not related to Cask itself. I'm aware of two common issues with downloading packages that apply regardless of whether Cask is being used:

- transient network/server issues: this appears to be quite common on Travis CI for the subject of the issue. Re-performing the installation seems to solve the problem. The fault is likely with the network or package server (see https://docs.travis-ci.com/user/common-build-problems/#Timeouts-installing-dependencies)
- TLS misconfiguration. This is becoming more and more of an issue from Emacs 26+, since insecure fallbacks were removed to some extent. You need to have your environment and Emacs built and configured properly for TLS.

These seems to cover the vast majority of comments here as well. If there are other issues not captured by external factors then new, more focussed issues can be created with specific information about Cask's culpability.

**Closed by sambrightman** 2018-01-23 15:53 UTC

**Comment by nhessler** [comment] 2018-01-23 16:05
could the readme either have a small tutorial or point at a small tutorial
for setting up TLS correctly in Emacs?

**Comment by sambrightman** [comment] 2018-01-23 17:32
No, certainly not a full tutorial. Cask is not an Emacs or TLS tutorial, and the issues are independent.

**Comment by cpitclaudel** [comment] 2018-02-04 15:25
Relevant (great debugging work @sambrightman!) https://emacs.stackexchange.com/questions/37805/m-x-list-package-fails-with-error-certificate-could-not-be-verified

**Comment by sambrightman** [comment] 2018-02-20 21:47
I think the sysadmin and I have fixed the elpa.gnu.org certificate, so these kind of problems should be eliminated in certain classes of setup.
