### ISSUE TITLE
Packages not in `Cask` file are still managed

### ISSUE THREAD

**Issue by jacksonrayhamilton** [cask/cask#320] opened 2015-11-07 05:23 UTC
I expect that by removing a package from my `Cask` file, I'm telling cask that "the package doesn't exist anymore;" so when I run `cask update`, that package isn't updated, and when I call `(cask-intialize)` in my init file, packages not in my `Cask` file aren't loaded.

Except, they are still updated, and they are still loaded. I'd prefer my `Cask` file to be a representation and a single source of truth for my list of packages. In order to achieve this, I've made of habit of deleting my `.cask` directory and reinstalling every time I want to update, because it's the simplest way to "forget about" packages I've stopped using. I'd prefer to just use `cask update`, because that's faster.

Should cask be updated to reference the `Cask` file (rather than consult the `.cask` directory) when deciding to update or load packages?

**Comment by lunaryorn** [comment] 2015-11-07 08:45
@jacksonrayhamilton Cask currently just relies on package.el for updates, i.e. it updates what package.el would update.  Anything else is difficult.

The API of package.el is limited, and we'd have to take care for potential dependency issues to gracefully handle the case where a package that you removed from your `Cask` is still a—possibly transitive—dependency of another package in your `Cask`.

I'd welcome a patch that addresses this issue, and binds `cask update` to the `Cask` file, even cleaning up packages, but as far as I'm personally concerned it's not a major issue.  I only use `cask` for developing packages and consider `.cask/` as some kind of a transient cache directory:  Easy to delete, easy to reproduce.

**Comment by DarwinAwardWinner** [comment] 2015-11-22 20:09
Hello! I've recently written a recursive dependency walking function with a view to accomplishing a similar task: automatically uninstalling any packages not required by my Cask file, without accidentally uninstalling dependencies of packages in the Cask file. I was initially planning to submit it for inclusion into pallet, but I'm wondering if it might logically make more sense in Cask? Please let me know if you are interested.

You can see my POC here: https://github.com/rdallasgray/pallet/issues/49#issuecomment-151605925

**Comment by DarwinAwardWinner** [comment] 2015-11-22 20:14
Wait, I just realized that `cask-installed-dependencies` exists. I would think that implementing an "uninstall non-required packages" function should be straightforward from that.

**Comment by DarwinAwardWinner** [comment] 2015-11-22 20:24
Is there anything wrong with this? 

```elisp
(let  ((all-installed
      (sort (mapcar #'epl-package-name (epl-installed-packages))
            #'string<))
       (cask-reqs
        (sort (mapcar #'cask-dependency-name (cask-installed-dependencies (cask-initialize) t))
            #'string<)))
  (message "You can uninstall the following packages: %S"
           (cl-set-difference all-installed cask-recreqs)))
```

**Comment by lunaryorn** [comment] 2015-11-22 20:44
@DarwinAwardWinner I think that this uninstalls dependencies of packages managed via Cask, and that'd be a bad thing to do.

**Comment by DarwinAwardWinner** [comment] 2015-11-22 20:45
No, it uses the DEEP argument to `cask-installed-dependencies`, so it should keep all Cask-managed packages plus all their recursive dependencies.

**Comment by jacksonrayhamilton** [comment] 2015-11-22 21:21
FTR, I'm not a fan of adding "package cleanup" functionality, unless it's the only way to accomplish my single-source-of-truth proposal. Packages consume a vanishing amount of disk space, so cleaning them seems obessive-compulsive. Ignoring unused ones would be equivalent to "uninstalling" them, and lets you be fickle about "reinstalling" (they're still there in case you want to reenable them).

**Comment by DarwinAwardWinner** [comment] 2015-11-22 21:24
Ok, it sounds like this functionality would go better in pallet then, where ignoring and uninstalling are not the same because package.el initializes all installed packages (I think) when Emacs starts.

**Comment by rejeep** [comment] 2015-11-23 11:03
Another alternative is to add a command for it.

**Comment by DarwinAwardWinner** [comment] 2015-11-23 16:26
Well, I submitted the pull request to Pallet, but you could pull the function into cask just as easily: https://github.com/rdallasgray/pallet/pull/50

**Comment by lunaryorn** [comment] 2015-11-23 17:08
@DarwinAwardWinner Ah, sorry, I missed that 😊

I think a command to clean packages would be a nice addition to Cask 🙂

**Comment by DarwinAwardWinner** [comment] 2015-11-24 18:46
Please let me and @rdallasgray know if you're looking at merging this into Cask by commenting here: rdallasgray/pallet#50, so I can let him know not to also merge it into Pallet.

**Comment by lunaryorn** [comment] 2015-11-25 16:55
@DarwinAwardWinner I'd merge such a request, so :+1: from me.  @rejeep, what's your opinion?

**Comment by DarwinAwardWinner** [comment] 2015-11-25 18:27
I don't think I'm familiar enough with Cask's internals to implement the command-line interface for it, but you can use the code from that pull request as a base. I should note that the code I wrote ignores version numbers, so you would probably want to fix that as well.

**Comment by rejeep** [comment] 2015-11-26 19:48
If someone is willing to write this, I accept it to be merged upstream. There are [tons of examples](https://github.com/cask/cask/blob/master/cask-cli.el#L369-L390) on commands, so it should be easy for anyone to implement this. There are also [tons of tests](https://github.com/cask/cask/blob/master/test/cask-api-test.el) to so that should also be easy to write.

**Comment by DarwinAwardWinner** [comment] 2015-11-26 22:57
Ok, I'll work on it when I have time.

**Comment by cpitclaudel** [comment] 2016-02-23 16:23
@DarwinAwardWinner +1 from me, this would be really nice to have.

**Comment by jacksonrayhamilton** [comment] 2016-02-23 19:30
Emacs 25 offers `package-autoremove`. Should "a command to clean packages" use that?

**Comment by cpitclaudel** [comment] 2016-02-23 19:36
I don't think so; as far as package.el is concerned, these packages were never removed.

**Comment by Fuco1** [comment] 2018-09-04 16:44
> Packages consume a vanishing amount of disk space, so cleaning them seems obsessive-compulsive. 

I'm not sure but I think `(package-initialize)` would still walk and load them which slows the startup and can be quite substantial if you leave 100+ packages around (which for an .emacs.d is not that unusual).  There's already #138 and #264 and the solution here is pretty much the same as those two I'll close this issue.

In the future I would like to enforce that `cask install` only leaves whatever is necessary and removes what is not in the `cask` file... but then we also load metadata from the package files so there already is "two sources of truth" which does not work with the OPs idea of

> I'd prefer my Cask file to be a representation and a single source of truth for my list of packages

**Closed by Fuco1** 2018-09-04 16:44 UTC
