### ISSUE TITLE
cask package truncates after ends here inconsistently

### ISSUE THREAD

**Issue by phillord** [cask/cask#286] opened 2015-03-18 13:40 UTC
Cask truncates source files in single file packages to the end of the "ends here" line. I don't think it should do this at all personally, because there might be some code after which either breaks the package when run from source when it runs after packaging or vice versa. In my case, it's cutting off org-mode
    
    ;; #+end_src

block closing comments which is causing problems.

Even if this is considered correct, it should be consistent -- currently this behaviour happens for single-package files but not multi-package files. So for example, this file:

    ;;; a.el --- boring file

    ;; Version: 0.1
    ;; Package-Requires:
    
    ;;; a.el ends here

    ;; After

looses the "after" comment, until you add this file:

    ;;; a-b.el --- boring file

    ;;; a-b.el ends here

    ;; After

Now neither of them do.

**Comment by lunaryorn** [comment] 2015-03-18 15:34
@phillord It's not Cask doing that, it's package.el, and as far as I know that's actually documented and expected behaviour.

It happens only for single file packages, because these are parsed by package.el in order to extract the package metadata.  For multi-file packages the metadata comes from the pkg descriptors, the individual Emacs Lisp files are never touched at all.

Closing.  It's not something that we can fix, or want to fix actually.

**Comment by lunaryorn** [comment] 2015-03-18 15:35
IOW, you must not have any code after the `ends here` footer, but that code **never** makes it past package.el.  If you do, your packages are broken.

**Closed** 2015-03-18 15:36 UTC

**Comment by phillord** [comment] 2015-03-18 16:28
Thanks anyway.
