### ISSUE TITLE
Wrong type argument: cask-dependency, error

### ISSUE THREAD

**Issue by zonuexe** [cask/cask#365] opened 2016-08-27 06:26 UTC
I'm using emacs-25.1rc2. [My `Cask` file](https://github.com/zonuexe/dotfiles/blob/master/.emacs.d/Cask).

```
% emacs --version
GNU Emacs 25.1.1
Copyright (C) 2016 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

% which cask
/Users/megurine/.cask/bin/cask

% cask --version
0.7.4
```

```
% cd ~/.emacs.d
% cask update
Wrong type argument: cask-dependency, error

% cask update --debug --verbose
Debugger entered--Lisp error: (wrong-type-argument cask-dependency error)
  signal(wrong-type-argument (cask-dependency error))
  (or (progn nil (and (vectorp (nth 0 data)) (>= (length (nth 0 data)) 8) (memq (aref (nth 0 data) 0) cl-struct-cask-dependency-tags) t)) (signal (quote wrong-type-argument) (list (quote cask-dependency) (nth 0 data))))
  (progn nil (or (progn nil (and (vectorp (nth 0 data)) (>= (length (nth 0 data)) 8) (memq (aref (nth 0 data) 0) cl-struct-cask-dependency-tags) t)) (signal (quote wrong-type-argument) (list (quote cask-dependency) (nth 0 data)))) (aref (nth 0 data) 1))
  (let* ((data (cdr err)) (dependency (progn nil (or (progn nil (and (vectorp ...) (>= ... 8) (memq ... cl-struct-cask-dependency-tags) t)) (signal (quote wrong-type-argument) (list (quote cask-dependency) (nth 0 data)))) (aref (nth 0 data) 1))) (message (error-message-string (nth 1 data))) (output (nth 2 data))) (if dependency (error "Dependency %s failed to install: %s\nOutput:\n%s" dependency message output) (error "Package installation failed: %s\nOutput:\n%s" message output)))
  (condition-case err (progn (let ((upgrades (cask-update (cask-cli--bundle)))) (if upgrades (progn (princ "Updated packages:\n") (-each upgrades (quote cask-cli--print-upgrade)))))) (cask-missing-dependencies (let ((missing-dependencies (cdr err))) (error "Some dependencies were not available: %s" (s-join ", " (-map (function symbol-name) (-map (function cask-dependency-name) missing-dependencies)))))) (cask-failed-initialization (let* ((data (cdr err)) (message (error-message-string (nth 0 data))) (output (nth 1 data))) (error "Package initialization failed: %s\nOutput:\n%s" message output))) (cask-failed-installation (let* ((data (cdr err)) (dependency (progn nil (or (progn nil ...) (signal ... ...)) (aref (nth 0 data) 1))) (message (error-message-string (nth 1 data))) (output (nth 2 data))) (if dependency (error "Dependency %s failed to install: %s\nOutput:\n%s" dependency message output) (error "Package installation failed: %s\nOutput:\n%s" message output)))))
  cask-cli/update()
  commander--handle-command(("update"))
  commander-parse(("update" "--debug" "--verbose"))
  (if commander-parsing-done nil (commander-parse (or commander-args (cdr command-line-args-left))))
  eval-buffer(#<buffer  *load*> nil "/Users/megurine/.cask/cask-cli.el" nil t)  ; Reading at buffer position 13463
  load-with-code-conversion("/Users/megurine/.cask/cask-cli.el" "/Users/megurine/.cask/cask-cli.el" nil t)
  load("/Users/megurine/.cask/cask-cli.el" nil t t)
  command-line-1(("-scriptload" "/Users/megurine/.cask/cask-cli.el" "--" "update" "--debug" "--verbose"))
  command-line()
  normal-top-level()
```

I could not clarify the cause of this problem.

**Comment by rejeep** [comment] 2016-08-28 11:23
I've tried your Cask-file and it works fine for me. Can you remove the `.cask` directory and try again?

**Comment by zonuexe** [comment] 2016-08-28 14:51
Hmm... Also erase the directory is the same behavior will occur.

**Comment by zonuexe** [comment] 2016-08-28 15:05
```patch
diff --git a/cask-cli.el b/cask-cli.el
index b5b2eff..ec99596 100644
--- a/cask-cli.el
+++ b/cask-cli.el
@@ -95,6 +95,7 @@
   (declare (indent 0))
   `(condition-case err
        (progn ,@body)
+     (error (princ err))
      (cask-missing-dependencies
       (let ((missing-dependencies (cdr err)))
         (error "Some dependencies were not available: %s"
```

```
% cask update --debug --verbose
(cask-failed-installation error (error Package ‘term+-20160404.355’ is used by ‘term+key-intercept’ as dependency, not deleting) )%
```

**Comment by rejeep** [comment] 2016-09-05 05:41
Then this is most likely related to Emacs 25, as I use 24 (you might also want to try and see if it works on 24). Closing as Emacs 25 is not released yet. If you do solve the issue yourself, I don't mind adding the fix, but I will not try to find it myself.

**Closed by rejeep** 2016-09-05 05:41 UTC

**Comment by UndeadKernel** [comment] 2016-09-20 07:59
Emacs 25 has been released and this problem still exists. Could we reopen this issue?

**Comment by lunaryorn** [comment] 2016-09-20 08:45
@UndeadKernel I am not convinced that this is an Emacs issue.  I've been using Emacs 25 since the first pretest and had no issues.

We can re-open the issue, but for us to fix this I think we either need someone who's affected to debug and fix the issue, or provide us with a *minimal* Cask file and a step-by-step recipe to reproduce the issue in a clean environment.

**Comment by phillord** [comment] 2016-09-22 13:07
I haven't used Cask with Emacs-24 for ages, so think it's not likely a 25 issue. A clean environment is definately the way to go.

**Comment by gongzhitaao** [comment] 2018-09-04 12:26
I run into this issue on Ubuntu 18.04
```
$ cask --version
0.8.4

$ emacs --version
GNU Emacs 25.2.2
[....]

$ cask update --verbose --debug
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Debugger entered--Lisp error: (wrong-type-argument cask-dependency error)
  signal(wrong-type-argument (cask-dependency error))
  (or (progn nil (and (vectorp (nth 0 data)) (>= (length (nth 0 data)) 8) (memq (aref (nth 0 data) 0) cl-struct-cask-dependency-tags) t)) (signal (quote wrong-type-argument) (list (quote cask-dependency) (nth 0 data))))
  (progn nil (or (progn nil (and (vectorp (nth 0 data)) (>= (length (nth 0 data)) 8) (memq (aref (nth 0 data) 0) cl-struct-cask-dependency-tags) t)) (signal (quote wrong-type-argument) (list (quote cask-dependency) (nth 0 data)))) (aref (nth 0 data) 1))
  (let* ((data (cdr err)) (dependency (progn nil (or (progn nil (and (vectorp ...) (>= ... 8) (memq ... cl-struct-cask-dependency-tags) t)) (signal (quote wrong-type-argument) (list (quote cask-dependency) (nth 0 data)))) (aref (nth 0 data) 1))) (message (error-message-string (nth 1 data))) (output (nth 2 data))) (if dependency (error "Dependency %s failed to install: %s\nOutput:\n%s" dependency message output) (error "Package installation failed: %s\nOutput:\n%s" message output)))
  (condition-case err (progn (let ((upgrades (cask-update (cask-cli--bundle)))) (if upgrades (progn (princ "Updated packages:\n") (-each upgrades (quote cask-cli--print-upgrade)))))) (cask-missing-dependencies (let ((missing-dependencies (cdr err))) (error "Some dependencies were not available: %s" (s-join ", " (-map (function symbol-name) (-map (function cask-dependency-name) missing-dependencies)))))) (cask-failed-initialization (let* ((data (cdr err)) (message (error-message-string (nth 0 data))) (output (nth 1 data))) (error "Package initialization failed: %s\nOutput:\n%s" message output))) (cask-failed-installation (let* ((data (cdr err)) (dependency (progn nil (or (progn nil ...) (signal ... ...)) (aref (nth 0 data) 1))) (message (error-message-string (nth 1 data))) (output (nth 2 data))) (if dependency (error "Dependency %s failed to install: %s\nOutput:\n%s" dependency message output) (error "Package installation failed: %s\nOutput:\n%s" message output)))))
  cask-cli/update()
  commander--handle-command(("update"))
  commander-parse(("update" "--verbose" "--debug"))
  (if commander-parsing-done nil (commander-parse (or commander-args (cdr command-line-args-left))))
  eval-buffer(#<buffer  *load*> nil "/home/gongzhitaao/.cask/cask-cli.el" nil t)  ; Reading at buffer position 13473
  load-with-code-conversion("/home/gongzhitaao/.cask/cask-cli.el" "/home/gongzhitaao/.cask/cask-cli.el" nil t)
  load("/home/gongzhitaao/.cask/cask-cli.el" nil t t)
  command-line-1(("-scriptload" "/home/gongzhitaao/.cask/cask-cli.el" "--" "update" "--verbose" "--debug"))
  command-line()
  normal-top-level()
```

**Comment by Fuco1** [comment] 2018-09-04 12:32
Can you check if there's a byte-compiled file `/home/gongzhitaao/.cask/cask-cli.elc` and if so delete it and try again?

**Comment by gongzhitaao** [comment] 2018-09-04 13:16
@Fuco1 It works.  I actually delete the whole `.cask` directory.
