### ISSUE TITLE
Installing distel from git

### ISSUE THREAD

**Issue by anquegi** [cask/cask#414] opened 2018-02-07 09:54 UTC
When I try to install distel from git using:

`(depends-on "distel" :git "https://github.com/massemanet/distel.git")`

I get the following error:

```
Debugger entered--Lisp error: (error "Dependency distel failed to install: Wrong type argument: sequencep, distel\nOutput:\n")
  signal(error ("Dependency distel failed to install: Wrong type argument: sequencep, distel\nOutput:\n"))
  error("Dependency %s failed to install: %s\nOutput:\n%s" distel "Wrong type argument: sequencep, distel" "")
  (if dependency (error "Dependency %s failed to install: %s\nOutput:\n%s" dependency message output) (error "Package installation failed: %s\nOutput:\n%s" message output))
  (let* ((data (cdr err)) (dependency (progn (or (and (memq (type-of (nth 0 data)) cl-struct-cask-dependency-tags) t) (signal 'wrong-type-argument (list 'cask-dependency (nth 0 data)))) (aref (nth 0 data) 1))) (message (error-message-string (nth 1 data))) (output (nth 2 data))) (if dependency (error "Dependency %s failed to install: %s\nOutput:\n%s" dependency message output) (error "Package installation failed: %s\nOutput:\n%s" message output)))
  (condition-case err (progn (cask-install (cask-cli--bundle))) (cask-missing-dependencies (let ((missing-dependencies (cdr err))) (error "Some dependencies were not available: %s" (s-join ", " (-map (function symbol-name) (-map (function cask-dependency-name) missing-dependencies)))))) (cask-failed-initialization (let* ((data (cdr err)) (message (error-message-string (nth 0 data))) (output (nth 1 data))) (error "Package initialization failed: %s\nOutput:\n%s" message output))) (cask-failed-installation (let* ((data (cdr err)) (dependency (progn (or (and (memq (type-of (nth 0 data)) cl-struct-cask-dependency-tags) t) (signal 'wrong-type-argument (list 'cask-dependency (nth 0 data)))) (aref (nth 0 data) 1))) (message (error-message-string (nth 1 data))) (output (nth 2 data))) (if dependency (error "Dependency %s failed to install: %s\nOutput:\n%s" dependency message output) (error "Package installation failed: %s\nOutput:\n%s" message output)))))
  cask-cli/install()
  commander--handle-command(("install"))
  commander-parse(("--debug" "install"))
  (if commander-parsing-done nil (commander-parse (or commander-args (cdr command-line-args-left))))
  eval-buffer(#<buffer  *load*> nil "/usr/local/Cellar/cask/0.8.1/cask-cli.el" nil t)  ; Reading at buffer position 13463
  load-with-code-conversion("/usr/local/Cellar/cask/0.8.1/cask-cli.el" "/usr/local/Cellar/cask/0.8.1/cask-cli.el" nil t)
  load("/usr/local/Cellar/cask/0.8.1/cask-cli.el" nil t t)
  command-line-1(("-scriptload" "/usr/local/Cellar/cask/0.8.1/cask-cli.el" "--" "--debug" "install"))
  command-line()
  normal-top-level()
```

**Comment by sambrightman** [comment] 2018-02-07 22:07
Duplicate of #407/#413 please check there and re-open if upgrading doesn’t solve it.

**Closed by sambrightman** 2018-02-07 22:07 UTC

**Comment by anquegi** [comment] 2018-02-09 08:28
Hi I upgrade to 0.8.2 with brew and it seems to go an step further, now it fails due to a file:

```
cask --verbose install                                                                                                                                                                                             
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Dependency distel failed to install: Single file distel.texi does not match package name distel
Output:
```
and with the `--debug` option:

```
Debugger entered--Lisp error: (error "Dependency distel failed to install: Single file distel.texi does not match package name distel\nOutput:\n")
  signal(error ("Dependency distel failed to install: Single file distel.texi does not match package name distel\nOutput:\n"))
  error("Dependency %s failed to install: %s\nOutput:\n%s" distel "Single file distel.texi does not match package name distel" "")
  (if dependency (error "Dependency %s failed to install: %s\nOutput:\n%s" dependency message output) (error "Package installation failed: %s\nOutput:\n%s" message output))
  (let* ((data (cdr err)) (dependency (progn (or (and (memq (type-of (nth 0 data)) cl-struct-cask-dependency-tags) t) (signal 'wrong-type-argument (list 'cask-dependency (nth 0 data)))) (aref (nth 0 data) 1))) (message (error-message-string (nth 1 data))) (output (nth 2 data))) (if dependency (error "Dependency %s failed to install: %s\nOutput:\n%s" dependency message output) (error "Package installation failed: %s\nOutput:\n%s" message output)))
  (condition-case err (progn (cask-install (cask-cli--bundle))) (cask-missing-dependencies (let ((missing-dependencies (cdr err))) (error "Some dependencies were not available: %s" (s-join ", " (-map (function symbol-name) (-map (function cask-dependency-name) missing-dependencies)))))) (cask-failed-initialization (let* ((data (cdr err)) (message (error-message-string (nth 0 data))) (output (nth 1 data))) (error "Package initialization failed: %s\nOutput:\n%s" message output))) (cask-failed-installation (let* ((data (cdr err)) (dependency (progn (or (and (memq (type-of (nth 0 data)) cl-struct-cask-dependency-tags) t) (signal 'wrong-type-argument (list 'cask-dependency (nth 0 data)))) (aref (nth 0 data) 1))) (message (error-message-string (nth 1 data))) (output (nth 2 data))) (if dependency (error "Dependency %s failed to install: %s\nOutput:\n%s" dependency message output) (error "Package installation failed: %s\nOutput:\n%s" message output)))))
  cask-cli/install()
  commander--handle-command(("install"))
  commander-parse(("--debug" "install"))
  (if commander-parsing-done nil (commander-parse (or commander-args (cdr command-line-args-left))))
  eval-buffer(#<buffer  *load*> nil "/usr/local/Cellar/cask/0.8.2/cask-cli.el" nil t)  ; Reading at buffer position 13466
  load-with-code-conversion("/usr/local/Cellar/cask/0.8.2/cask-cli.el" "/usr/local/Cellar/cask/0.8.2/cask-cli.el" nil t)
  load("/usr/local/Cellar/cask/0.8.2/cask-cli.el" nil t t)
  command-line-1(("-scriptload" "/usr/local/Cellar/cask/0.8.2/cask-cli.el" "--" "--debug" "install"))
  command-line()
  normal-top-level()
```

**Comment by sambrightman** [comment] 2018-02-09 15:32
This isn't a Cask issue; `distel` is not `package-build` compatible in its default directory. I suggest contacting the author if you feel this should change, but I see that massemanet/distel#59 has already been open and unattended for a while.

In the meantime, please see [the documentation for `depends-on`](http://cask.readthedocs.io/en/latest/guide/dsl.html#el.function.depends-on). Something like this should work:

    (depends-on "distel" :git "https://github.com/massemanet/distel.git" :files ("elisp/*.el" "doc/*.texi"))                                                                                                                                                                                                                     

From Cask 0.9 this would be better:

    (depends-on "distel" :git "https://github.com/massemanet/distel.git" :files (:defaults "elisp/*.el"))

**Comment by anquegi** [comment] 2018-02-11 18:03
Hi thanks, for the explanation, it worked well for downloading, but not for directly working with this package, you also need to make the package, thanks for carrying this and give me the pertinent explanations
